/*
 * This file is generated by jOOQ.
 */
package com.city.api.cityAPI.jooq.sample.model;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class City extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>city</code>
     */
    public static final City CITY = new City();

    /**
     * The table <code>city.city</code>.
     */
    public final com.city.api.cityAPI.jooq.sample.model.tables.City CITY_ = com.city.api.cityAPI.jooq.sample.model.tables.City.CITY_;

    /**
     * No further instances allowed
     */
    private City() {
        super("city", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            com.city.api.cityAPI.jooq.sample.model.tables.City.CITY_);
    }
}
