/*
 * This file is generated by jOOQ.
 */
package com.city.api.cityAPI.jooq.sample.model;


import com.city.api.cityAPI.jooq.sample.model.tables.City;
import com.city.api.cityAPI.jooq.sample.model.tables.records.CityRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * city.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CityRecord> PRIMARY_KEY = Internal.createUniqueKey(City.CITY_, DSL.name("PRIMARY_KEY"), new TableField[] { City.CITY_.IBGE_ID }, true);
    public static final UniqueKey<CityRecord> UNIQUE_KEY = Internal.createUniqueKey(City.CITY_, DSL.name("UNIQUE_KEY"), new TableField[] { City.CITY_.UF, City.CITY_.NAME }, true);
}
