/*
 * This file is generated by jOOQ.
 */
package com.city.api.cityAPI.jooq.sample.model;


import com.city.api.cityAPI.jooq.sample.model.tables.City;


/**
 * Convenience access to all tables in city.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>city.city</code>.
     */
    public static final City CITY_ = City.CITY_;
}
