/*
 * This file is generated by jOOQ.
 */
package com.city.api.cityAPI.jooq.sample.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class City implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long    ibgeId;
    private String  uf;
    private String  name;
    private Boolean isCapital;
    private Double  longitude;
    private Double  latitude;
    private String  alternativeNames;
    private String  microregion;
    private String  mesoregion;

    public City() {}

    public City(City value) {
        this.ibgeId = value.ibgeId;
        this.uf = value.uf;
        this.name = value.name;
        this.isCapital = value.isCapital;
        this.longitude = value.longitude;
        this.latitude = value.latitude;
        this.alternativeNames = value.alternativeNames;
        this.microregion = value.microregion;
        this.mesoregion = value.mesoregion;
    }

    public City(
        Long    ibgeId,
        String  uf,
        String  name,
        Boolean isCapital,
        Double  longitude,
        Double  latitude,
        String  alternativeNames,
        String  microregion,
        String  mesoregion
    ) {
        this.ibgeId = ibgeId;
        this.uf = uf;
        this.name = name;
        this.isCapital = isCapital;
        this.longitude = longitude;
        this.latitude = latitude;
        this.alternativeNames = alternativeNames;
        this.microregion = microregion;
        this.mesoregion = mesoregion;
    }

    /**
     * Getter for <code>city.city.ibge_id</code>.
     */
    public Long getIbgeId() {
        return this.ibgeId;
    }

    /**
     * Setter for <code>city.city.ibge_id</code>.
     */
    public City setIbgeId(Long ibgeId) {
        this.ibgeId = ibgeId;
        return this;
    }

    /**
     * Getter for <code>city.city.uf</code>.
     */
    public String getUf() {
        return this.uf;
    }

    /**
     * Setter for <code>city.city.uf</code>.
     */
    public City setUf(String uf) {
        this.uf = uf;
        return this;
    }

    /**
     * Getter for <code>city.city.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>city.city.name</code>.
     */
    public City setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>city.city.is_capital</code>.
     */
    public Boolean getIsCapital() {
        return this.isCapital;
    }

    /**
     * Setter for <code>city.city.is_capital</code>.
     */
    public City setIsCapital(Boolean isCapital) {
        this.isCapital = isCapital;
        return this;
    }

    /**
     * Getter for <code>city.city.longitude</code>.
     */
    public Double getLongitude() {
        return this.longitude;
    }

    /**
     * Setter for <code>city.city.longitude</code>.
     */
    public City setLongitude(Double longitude) {
        this.longitude = longitude;
        return this;
    }

    /**
     * Getter for <code>city.city.latitude</code>.
     */
    public Double getLatitude() {
        return this.latitude;
    }

    /**
     * Setter for <code>city.city.latitude</code>.
     */
    public City setLatitude(Double latitude) {
        this.latitude = latitude;
        return this;
    }

    /**
     * Getter for <code>city.city.alternative_names</code>.
     */
    public String getAlternativeNames() {
        return this.alternativeNames;
    }

    /**
     * Setter for <code>city.city.alternative_names</code>.
     */
    public City setAlternativeNames(String alternativeNames) {
        this.alternativeNames = alternativeNames;
        return this;
    }

    /**
     * Getter for <code>city.city.microregion</code>.
     */
    public String getMicroregion() {
        return this.microregion;
    }

    /**
     * Setter for <code>city.city.microregion</code>.
     */
    public City setMicroregion(String microregion) {
        this.microregion = microregion;
        return this;
    }

    /**
     * Getter for <code>city.city.mesoregion</code>.
     */
    public String getMesoregion() {
        return this.mesoregion;
    }

    /**
     * Setter for <code>city.city.mesoregion</code>.
     */
    public City setMesoregion(String mesoregion) {
        this.mesoregion = mesoregion;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final City other = (City) obj;
        if (ibgeId == null) {
            if (other.ibgeId != null)
                return false;
        }
        else if (!ibgeId.equals(other.ibgeId))
            return false;
        if (uf == null) {
            if (other.uf != null)
                return false;
        }
        else if (!uf.equals(other.uf))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (isCapital == null) {
            if (other.isCapital != null)
                return false;
        }
        else if (!isCapital.equals(other.isCapital))
            return false;
        if (longitude == null) {
            if (other.longitude != null)
                return false;
        }
        else if (!longitude.equals(other.longitude))
            return false;
        if (latitude == null) {
            if (other.latitude != null)
                return false;
        }
        else if (!latitude.equals(other.latitude))
            return false;
        if (alternativeNames == null) {
            if (other.alternativeNames != null)
                return false;
        }
        else if (!alternativeNames.equals(other.alternativeNames))
            return false;
        if (microregion == null) {
            if (other.microregion != null)
                return false;
        }
        else if (!microregion.equals(other.microregion))
            return false;
        if (mesoregion == null) {
            if (other.mesoregion != null)
                return false;
        }
        else if (!mesoregion.equals(other.mesoregion))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.ibgeId == null) ? 0 : this.ibgeId.hashCode());
        result = prime * result + ((this.uf == null) ? 0 : this.uf.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.isCapital == null) ? 0 : this.isCapital.hashCode());
        result = prime * result + ((this.longitude == null) ? 0 : this.longitude.hashCode());
        result = prime * result + ((this.latitude == null) ? 0 : this.latitude.hashCode());
        result = prime * result + ((this.alternativeNames == null) ? 0 : this.alternativeNames.hashCode());
        result = prime * result + ((this.microregion == null) ? 0 : this.microregion.hashCode());
        result = prime * result + ((this.mesoregion == null) ? 0 : this.mesoregion.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("City (");

        sb.append(ibgeId);
        sb.append(", ").append(uf);
        sb.append(", ").append(name);
        sb.append(", ").append(isCapital);
        sb.append(", ").append(longitude);
        sb.append(", ").append(latitude);
        sb.append(", ").append(alternativeNames);
        sb.append(", ").append(microregion);
        sb.append(", ").append(mesoregion);

        sb.append(")");
        return sb.toString();
    }
}
